# $FreeBSD$

TESTSDIR=	${TESTSBASE}/sys/netpfil/pf/files
BINDIR=		${TESTSDIR}

FILES=		pf_test_conf.sh pf_test_util.sh \
		scrub_forward.py scrub6.py conf.py util.py
		vmctl.sh make_baseimg.sh

.include <bsd.progs.mk>
